worker_processes 1;
events {
    worker_connections 1024;
}
http {
    server {
        listen 8080;
        root .;
        add_header 'Access-Control-Allow-Origin' '*';
        types {
            application/wasm wasm;
            application/javascript js;
            text/html html;
            application/json json;
            text/plain txt;
        }
    }
}
