#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["whoosh-reloaded>=2.7.5"]
# ///
"""Tests for scripts/whoosh_oracle.py (item00: three modes, sizes, battery).

Run: ./scripts/test_whoosh_oracle.py
Plain asserts, no test framework. Exits non-zero on any failure.

The shipped JSONL is regenerated by item01, so the core tests are
data-agnostic: they cross-check the oracle against an independent plain-json
recomputation of whatever the snapshot contains. The spec's ground-truth
numbers (995 found / 983 indexed / 12 rejected, dupes {20141204: 2,
20150323: 2}, consensus = 72 whoosh hits, 993 reachable md docs) are verified
in test_ground_truth_prefixture against the permanent pre-fix artifact
(.tmp/delegation/shipped_search_data_before_item01.jsonl, recovered from git
HEAD); that test skips if the artifact is absent.
"""
from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))

import whoosh_oracle as wo  # noqa: E402

SNAPSHOT = REPO / ".tmp" / "delegation" / "shipped_search_data.jsonl"
BEFORE = REPO / ".tmp" / "delegation" / "shipped_search_data_before_item01.jsonl"
REPORT = REPO / ".tmp" / "delegation" / "reports" / "item00-test.md"

BATTERY_KEYS = {
    "blockchai", "quantum blockchain", "consensus", "consensuz~2",
    "paxos consensus", "distributed transactions", "compiler optimization",
}


def snapshot_stats(path: Path):
    """Independent recomputation of the JSONL audit numbers."""
    total = indexed = 0
    rejected_dates = []
    dates = Counter()
    for line in path.read_text().splitlines():
        if not line.strip():
            continue
        total += 1
        doc = json.loads(line)
        missing = [f for f in ("date", "slug", "paper_title") if not doc.get(f)]
        bad = [f for f in ("paper_authors", "topics", "tags")
               if not isinstance(doc.get(f), list)]
        if not isinstance(doc.get("paper_year"), int):
            bad.append("paper_year")
        if missing or bad:
            rejected_dates.append(doc.get("date"))
            continue
        indexed += 1
        dates[doc["date"]] += 1
    dupes = {d: n for d, n in dates.items() if n > 1}
    return total, indexed, rejected_dates, dupes


def test_default_uses_snapshot():
    """Default mode must copy the shipped JSONL to the snapshot and audit that."""
    assert wo.parse_source("default")[1] is not None
    assert SNAPSHOT.exists(), "snapshot .tmp/delegation/shipped_search_data.jsonl not created"
    schema, docs, failures, total = wo.parse_source("default")
    exp_total, exp_indexed, exp_rejected, _ = snapshot_stats(SNAPSHOT)
    assert total == exp_total, f"found {total} != snapshot lines {exp_total}"
    assert len(docs) == exp_indexed, f"indexed {len(docs)} != {exp_indexed}"
    assert len(failures) == total - exp_indexed, "rejection count inconsistent"
    blob = " ".join(str(f) for f in failures)
    for d in exp_rejected:
        assert d in blob, f"rejected list missing date {d}"


def test_pages_corpus():
    """--pages mode: all 995 pages/*.json docs, tantivy-lenient field coercion."""
    schema, docs, failures, total = wo.parse_source("pages")
    assert total == 995, f"pages records {total} != 995"
    assert len(docs) == 995, f"pages indexed {len(docs)} != 995"
    assert not failures, f"pages rejects docs: {failures[:3]}"
    dates = {d["date"] for d in docs}
    assert "20141204-2" in dates and "20150323-2" in dates, "sync-copy stems missing"
    zero_year = [d for d in docs if d["paper_year"] == 0]
    assert zero_year, "no doc with paper_year coerced to 0"
    for d in docs:
        for f in ("paper_title", "paper_venue", "blog_summary", "paper_abstract"):
            assert isinstance(d[f], str), f"{d['date']}.{f} not a str: {d[f]!r}"


def test_md_corpus():
    """--md mode: reachable set only (JSONL date AND pages/<date>.md), full body."""
    schema, docs, unreachable = wo.parse_md()
    md_stems = {p.stem for p in wo.PAGES.glob("*.md")}
    jsonl_dates = wo.jsonl_date_set()
    exp_reachable = md_stems & jsonl_dates
    exp_unreachable = sorted(md_stems - jsonl_dates)
    assert len(docs) == len(exp_reachable), \
        f"md docs {len(docs)} != reachable {len(exp_reachable)}"
    assert sorted(unreachable) == exp_unreachable, \
        f"unreachable {sorted(unreachable)} != {exp_unreachable}"
    for d in docs:
        assert d["date"] and d["slug"], f"md doc missing ids: {d['date']!r}"
        assert d["body"].strip(), f"md doc {d['date']} has empty body"
        assert "blog_url:" not in d["body"], f"md doc {d['date']} body still has front matter"


def test_build_report():
    """build --report writes a compact markdown report with counts + battery."""
    schema, docs, _, _ = wo.parse_source("md")
    wo.build("md", report_path=REPORT)
    text = REPORT.read_text()
    assert "mode: md" in text
    assert str(len(docs)) in text, "doc count missing from report"
    assert "unreachable" in text.lower(), "unreachable list missing from report"
    assert "bytes" in text.lower(), "index size missing from report"
    assert "consensus" in text, "battery counts missing from report"


def test_battery_counts_default():
    wo.build("default")
    counts = wo.battery_counts("default")
    assert set(counts) == BATTERY_KEYS, f"battery keys mismatch: {sorted(counts)}"
    assert all(isinstance(v, int) and v >= 0 for v in counts.values()), counts


def test_battery_counts_pages_and_md():
    for mode in ("pages", "md"):
        wo.build(mode)
        counts = wo.battery_counts(mode)
        assert set(counts) == BATTERY_KEYS, f"{mode}: keys {sorted(counts)}"
        assert counts["consensus"] > 0, f"{mode}: consensus got 0 hits"


def test_default_regression_search():
    """Existing default-mode behaviour keeps working: search + fuzzy return hits."""
    wo.build("default")
    hits = wo.search("paxos consensus", limit=5, mode="default", quiet=True)
    assert len(hits) > 0, "default search returned no hits"
    fhits = wo.fuzzy("consensuz", dist=2, limit=5, mode="default", quiet=True)
    assert len(fhits) > 0, "default fuzzy returned no hits"


def test_ground_truth_prefixture():
    """Audit the permanent pre-fix artifact and reproduce the spec's numbers."""
    if not BEFORE.exists():
        print(f"SKIP test_ground_truth_prefixture (no {BEFORE.name})")
        return
    original_jsonl = wo.JSONL
    try:
        wo.JSONL = BEFORE
        _, docs, failures, total = wo.parse_source("default")
        assert total == 995, f"pre-fix found {total} != 995"
        assert len(docs) == 983, f"pre-fix indexed {len(docs)} != 983"
        assert len(failures) == 12, f"pre-fix rejected {len(failures)} != 12"
        dupes = Counter(d["date"] for d in docs)
        assert {k: v for k, v in dupes.items() if v > 1} == {"20141204": 2, "20150323": 2}, \
            "pre-fix duplicate dates not as spec"
        wo.build("default")
        counts = wo.battery_counts("default")
        assert counts["consensus"] == 72, \
            f"pre-fix consensus {counts['consensus']} != 72 (spec ground truth)"
        _, md_docs, unreachable = wo.parse_md()
        assert len(md_docs) == 993, f"pre-fix md docs {len(md_docs)} != 993"
        assert sorted(unreachable) == ["20141204-2", "20150323-2"], \
            f"pre-fix unreachable {sorted(unreachable)}"
    finally:
        wo.JSONL = original_jsonl


FUNCTIONS = [
    test_default_uses_snapshot,
    test_pages_corpus,
    test_md_corpus,
    test_build_report,
    test_battery_counts_default,
    test_battery_counts_pages_and_md,
    test_default_regression_search,
    test_ground_truth_prefixture,
]


def main() -> int:
    failed = []
    for fn in FUNCTIONS:
        try:
            fn()
            print(f"PASS {fn.__name__}")
        except AssertionError as e:
            failed.append(fn.__name__)
            print(f"FAIL {fn.__name__}: {e}")
        except Exception as e:  # noqa: BLE001
            failed.append(fn.__name__)
            print(f"ERROR {fn.__name__}: {type(e).__name__}: {e}")
    print(f"\n{len(FUNCTIONS) - len(failed)}/{len(FUNCTIONS)} passed")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
